DEFINE sql:select-option "order"
PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#>
PREFIX glytoucan: <http://www.glytoucan.org/glyco/owl/glytoucan#>
PREFIX user: <http://rdf.glycoinfo.org/glytoucan/contributor/userId/>

SELECT DISTINCT ?AccNum ?MassLabel ?CreateDate ?WurcsLabel 
WHERE {
    # Contributor
    VALUES ?user { user:{{userId}} }
    ?r_entry glytoucan:contributor ?user .
    ?r_entry glytoucan:date_registered ?date .
    BIND(STR(?date) AS ?CreateDate) 
    ?glycan glycan:has_resource_entry ?r_entry .

    # Accession Number
    ?glycan glytoucan:has_primary_id ?AccNum  .

    # Mass
    OPTIONAL{
    ?glycan glytoucan:has_derivatized_mass ?dmass .
    ?dmass rdfs:label ?msLabel .
    BIND(STR(?msLabel) AS ?MassLabel) 
    }

    # WURCS
    OPTIONAL{
    ?glycan glycan:has_glycosequence ?wcsSeq .
    ?wcsSeq glycan:in_carbohydrate_format glycan:carbohydrate_format_wurcs .
    ?wcsSeq rdfs:label ?wcsLabel .
    BIND(STR(?wcsLabel) AS ?WurcsLabel)
    } 
    
    # user id
    ?user dcterms:identifier ?userId.
    # user name
    ?user foaf:name ?userName .
} 
order by desc(?CreateDate)
LIMIT 20
OFFSET {{offset}}
